# Logistic Regression (Iris dataset)

In [105]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [106]:
df=sns.load_dataset('iris')
df.to_csv('Iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [107]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [109]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [110]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [111]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [112]:
# select features and labels
# x=df.drop(columns=['species'])
x = df[["petal_length" ,"sepal_width" , "petal_width" ,"sepal_length"]]
y=df['species'].map({'setosa':0,'versicolor':1,'virginica':2})

In [113]:
df.shape

(150, 5)

In [114]:
#split data for training and testing 
x_train,x_test,y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [115]:
#normalization
scaler=StandardScaler()
x_train,x_test=scaler.fit_transform(x_train),scaler.transform(x_test)

In [116]:
model=LogisticRegression(max_iter=200)

In [117]:
#feeding data to model to understanding
model.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [118]:
#score
t_score=model.score(x_train,y_train)
print("Accuracy score: ",t_score)

Accuracy score:  0.9666666666666667


In [119]:
#prediction
y_predict=model.predict(x_test)
y_predict

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [120]:
# accuracy score
accuracy=accuracy_score(y_test,y_predict)
print("Accuracy of prediction: ",accuracy)

Accuracy of prediction:  1.0


In [121]:
# confusion metrix
cm=confusion_matrix(y_test,y_predict)
print("Confusion Metrix: ",cm)

Confusion Metrix:  [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [122]:
#classification report
from sklearn.metrics import classification_report
print("Classification Report",classification_report(y_test,y_predict))

Classification Report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

